#!/usr/bin/env bash
set -e

readonly DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

for testfile in "$@"; do
  stack runghc \
        --resolver lts-16.10 \
        --package shake \
        --package regex-base \
        --package regex-tdfa \
        --package strip-ansi-escape \
        $DIR/runner.hs $DIR/../src/ $testfile
done
